### ISSUE TITLE
Defaults ignored via Admin Panel

### ISSUE THREAD

**Issue by n1xn** [lucasgiovanny/filament-multiselect-two-sides#12]
Right hand side is empty in resource edit mode.  For this example I am using the `UserResource` which have a relation to `Test` Model, therefore I am loading the options because there are conditions to it based on the previous selection. The `User` model can have multiple `Test` models.

```
                    MultiselectTwoSides::make('tests')
                        ->options(function (callable $get) {
                            return Test::where('something_id', '=', null)
                                ->where('tenant_id', '=', $get('tenant_id'))
                                ->pluck('code', 'id');
                        })
                        ->default(Test::where('something_id', '=', $record->id)->pluck('code', 'id'))
                        ->required(),
```

**Comment by thiago-a-delgado** [comment]
According to the documentation, I believe you should only enter the key in the "default" array. In your case, I imagine you should pass a simple array, with just the "code" field.

> Right hand side is empty in resource edit mode. For this example I am using the `UserResource` which have a relation to `Test` Model, therefore I am loading the options because there are conditions to it based on the previous selection. The `User` model can have multiple `Test` models.
> 
> ```
>                     MultiselectTwoSides::make('tests')
>                         ->options(function (callable $get) {
>                             return Test::where('something_id', '=', null)
>                                 ->where('tenant_id', '=', $get('tenant_id'))
>                                 ->pluck('code', 'id');
>                         })
>                         ->default(Test::where('something_id', '=', $record->id)->pluck('code', 'id'))
>                         ->required(),
> ```
