### ISSUE TITLE
Different multi-select-two-sides fields in same form act like one input field

### ISSUE THREAD

**Issue by rixtrayker** [lucasgiovanny/filament-multiselect-two-sides#6]
**Reproduction steps:** 

1. create 2 selects in same form
2. try to select item from first one, it's selected in second one, check 
3. **Another possible Bug** it filters on name not the id some duplicate names considered as one item check 1st and 2nd screenshots

I found a work a round, it's to manipulate each data list IDs and add a suffix  or a prefix such (1_1, 1_2, 1_3)  for the first options list and (2_1, 2_2, 2_3 ) for the second options list 
<img width="698" alt="Screenshot 2023-03-07 at 7 52 19 PM" src="https://user-images.githubusercontent.com/7710590/223509202-3e692f40-0929-4d26-aa00-c6c945c15d86.png">
<img width="698" alt="Screenshot 2023-03-07 at 7 52 25 PM" src="https://user-images.githubusercontent.com/7710590/223509197-a3a3e083-2d19-4155-b5c2-a3b70dabec72.png">
<img width="698" alt="Screenshot 2023-03-07 at 7 52 29 PM" src="https://user-images.githubusercontent.com/7710590/223509190-5536ea72-824a-471e-a090-c2cc5c438a27.png">

**Comment by lucasgiovanny** [comment]
Good call! I will work on a fix for this soon to allow use multiple fields on the same form.

**Comment by rixtrayker** [comment]
@lucasgiovanny is that works well with many multi-select-two-sides with same array of data because if I selected one in first tab it's selected in second tab  ?
